// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(KiCoKalenderContext))]
    [Migration("20211003203331_fix3")]
    partial class fix3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Family", b =>
                {
                    b.Property<long?>("familyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("childrenIds")
                        .HasColumnType("bigint");

                    b.Property<string>("familyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("parentIds")
                        .HasColumnType("bigint");

                    b.HasKey("familyId");

                    b.ToTable("Family");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<long?>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("userAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userAge")
                        .HasColumnType("int");

                    b.Property<DateTime>("userCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("userFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userRole")
                        .HasColumnType("int");

                    b.Property<string>("userZipcode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
